name: Build Electron App

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x64, arm64]
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build Electron app
      run: npm run build
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ELECTRON_ARCH: ${{ matrix.arch }}
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mac-${{ matrix.arch }}-build
        path: dist/*.dmg